language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install -r requirements/development.txt
  - pip install coveralls
before_script:
  - sudo su - postgres -c "createuser -s vagrant"
  - flake8 acamar/ --ignore=E128,F403
script:
  - coverage run --source=acamar acamar/manage.py test acamar
after_success:
  coveralls
